Add templates to Github repository
Springo/Project-Euler-Library-Code pull request #4
Opened 2017-08-02 20:36 UTC by Springo

## Goal
Make Github repository more organized.

## Things To Do
- [x] Add pull request template.
- [ ] Add issue template.
- [ ] Add contributing readme.

2017-08-03 14:20 UTC, Springo commented
@irenfro Could you review the issue template I added? Afterwards, I'll leave the CONTRIBUTING.md file to you if you've got ideas for that before we merge this PR.

2017-08-04 00:42 UTC, irenfro commented on .github/ISSUE_TEMPLATE.md
> +## Description
We should split the description up into 2 fields: Current Behavior and Expected Behavior

2017-08-04 00:45 UTC, irenfro requested changes
@Springo just look at these two and I think you should be good

2017-08-04 00:45 UTC, irenfro commented on .github/ISSUE_TEMPLATE.md
> +## Solution Ideas
Before this we need something like: Minimal reproduction of the problem with instructions

2017-08-04 00:45 UTC, irenfro commented on .github/ISSUE_TEMPLATE.md
> +## Description
We should split the description up into 2 fields: Current Behavior and Expected Behavior

2017-08-11 00:11 UTC, Springo commented on CONTRIBUTING.md
> +## Pull Request Guidelines
I think the pull request section should be based off our template (which we can change).

2017-08-11 00:11 UTC, Springo commented on CONTRIBUTING.md
> +3. Go to VCS->Git->Rebase.
I would prefer that our method of merging in pull requests doesn't require another software. I think all of these instructions should be written with respect to Git Bash.

2017-08-11 00:11 UTC, Springo commented on CONTRIBUTING.md
> +3. Go to VCS->Git->Rebase.
If that's too complicated, I think we might want to use a simpler method of merging in pull requests for a standard pull request.

2017-08-11 00:11 UTC, Springo commented on CONTRIBUTING.md
> +fix: sytax error on function
Whoops, spelling error here.

2017-08-15 08:19 UTC, Springo commented
@irenfro Your changes look good to me, do you approve of my earlier changes to the issue and PR templates?

2017-08-15 15:43 UTC, irenfro commented
@Springo yep they look good to me

2017-08-15 19:06 UTC, merged